export default [
  {
    poster: "https://image.tmdb.org/t/p/w500/nOZyq3GLpjsWWaB0PD3wjpzNNZq.jpg",
    title: "Girl with a Pearl Earring",
    character: "Griet",
    overview:
      'This film, adapted from a work of fiction by author Tracy Chevalier, tells a story about the events surrounding the creation of the painting "Girl With A Pearl Earring" by 17th century Dutch master Johannes Vermeer. A young peasant maid working in the house of painter Johannes Vermeer becomes his talented assistant and the model for one of his most famous works.',
    release_date: "2003-12-12",
    average_rating: 6.6,
    type: "movie",
    id: 3635,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/gjdUhi3Q8BHFFmFLvVtjInUYdBM.jpg",
    title: "Vicky Cristina Barcelona",
    character: "Cristina",
    overview:
      "Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.",
    release_date: "2008-08-15",
    average_rating: 6.8,
    type: "movie",
    id: 5038,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/8hX6rcxnCidaqegPCyeFm9PODBn.jpg",
    title: "The Nanny Diaries",
    character: "Annie Braddock",
    overview:
      "A college graduate goes to work as a nanny for a rich New York family. Ensconced in their home, she has to juggle their dysfunction, a new romance, and the spoiled brat in her charge.",
    release_date: "2007-08-24",
    average_rating: 6.3,
    type: "movie",
    id: 12435,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/lXkWyYiMKx3o187CYH7fcrzEjAJ.jpg",
    title: "An American Rhapsody",
    character: "Suzanne Sandor",
    overview:
      "A Hungarian family forced to flee the Communist country for the United States, must leave a young daughter behind. Six years later the family arranges to bring the absent daughter to the United States where she has trouble adjusting. The daughter then decides to travel to Budapest to discover her identity.",
    release_date: "2001-06-22",
    average_rating: 6.5,
    type: "movie",
    id: 37920,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/1SqFTFpoxOXru9g1PTl9Tkjgfgb.jpg",
    title: "My Brother the Pig",
    character: "Kathy Caldwell",
    overview:
      "When a mysterious spell transforms a young teenager's bratty little brother into a pig while their parents are on vacation, their only hope for restoring the hoofed youngster back to his human form is to take a trip south of the border in this supernatural comedy for the whole family starring Scarlett Johansson. For years, Kathy Cauldwell (Johansson) has been the target of younger brother George's obnoxious practical jokes. Soon after Kathy and George's parents leave the youngsters in the care of nanny Matilda (Eva Mendes) in order to get away for a much-needed vacation in France, George is transformed into a pig thanks to Matilda's ancient magical rocks. As the trio sets off to Mexico to seek the help of Matilda's Mexican grandmother with George's best friend Freud in tow (Alex D. Linz), matters are complicated when a local butcher sets his sights on the portly new ham in town.",
    release_date: "1999-09-10",
    average_rating: 5.5,
    type: "movie",
    id: 73257,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/55wmcXJIDYITr7JDijJTdvwSaAv.jpg",
    title: "Under the Skin",
    character: "The Female",
    overview:
      "A seductive alien prowls the streets of Glasgow in search of prey: unsuspecting men who fall under her spell.",
    release_date: "2014-03-14",
    average_rating: 6.1,
    type: "movie",
    id: 97370,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/qAAeCBT0SOfXCPWxAH2DChw14k3.jpg",
    title: "Manny & Lo",
    character: "Amanda",
    overview:
      "A pregnant teen and her younger sister run away from foster homes and kidnap a woman whom they believe can help with the pregnancy.",
    release_date: "1996-01-22",
    average_rating: 6.3,
    type: "movie",
    id: 88224,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/kRbpUTRNm6QbLQFPFWUcNC4czEm.jpg",
    title: "Lucy",
    character: "Lucy Miller",
    overview:
      "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
    release_date: "2014-07-25",
    average_rating: 6.4,
    type: "movie",
    id: 240832,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/ttC00xcQ5UIO04kU8y0h5OAIYYJ.jpg",
    title: "Rough Night",
    character: "Jess Thayer",
    overview:
      "Five best friends from college reunite 10 years later for a wild bachelorette weekend in Miami. Their hard partying takes a hilariously dark turn when they accidentally kill a male stripper. Amidst the craziness of trying to cover it up, they're ultimately brought closer together when it matters most.",
    release_date: "2017-06-15",
    average_rating: 5.7,
    type: "movie",
    id: 397422,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/myRzRzCxdfUWjkJWgpHHZ1oGkJd.jpg",
    title: "Ghost in the Shell",
    character: "Major Mira Killian / Motoko Kusanagi",
    overview:
      "In the near future, Major is the first of her kind: a human saved from a terrible crash, then cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.",
    release_date: "2017-03-29",
    average_rating: 6,
    type: "movie",
    id: 315837,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    title: "Black Widow",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
    release_date: "2021-07-07",
    average_rating: 7.9,
    type: "movie",
    id: 497698,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
    title: "Lost in Translation",
    character: "Charlotte",
    overview:
      "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
    release_date: "2003-09-18",
    average_rating: 7.4,
    type: "movie",
    id: 153,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/9u8MAGTAAhIdqZfhNsHcLcRNnra.jpg",
    title: "In Good Company",
    character: "Alex Foreman",
    overview:
      "Dan Foreman is a seasoned advertisement sales executive at a high-ranking publication when a corporate takeover results in him being placed under naive supervisor Carter Duryea, who is half his age. Matters are made worse when Dan's new supervisor becomes romantically involved with his daughter an 18 year-old college student Alex.",
    release_date: "2004-12-29",
    average_rating: 6,
    type: "movie",
    id: 1901,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/g9qawfzR3LWRC8r8YZ9w2yaQi5W.jpg",
    title: "The Spirit",
    character: "Silken Floss",
    overview:
      "Down these mean streets a man must come.  A hero born, murdered, and born again.  A Rookie cop named Denny Colt returns from the beyond as The Spirit, a hero whose mission is to fight against the bad forces from the shadows of Central City.  The Octopus, who kills anyone unfortunate enough to see his face, has other plans; he is going to wipe out the entire city.",
    release_date: "2008-12-25",
    average_rating: 4.7,
    type: "movie",
    id: 8285,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/9zD3hXV24zJzYvSuakXZU8yMEY4.jpg",
    title: "The Other Boleyn Girl",
    character: "Mary Boleyn",
    overview:
      "A sumptuous and sensual tale of intrigue, romance and betrayal set against the backdrop of a defining moment in European history: two beautiful sisters, Anne and Mary Boleyn, driven by their family's blind ambition, compete for the love of the handsome and passionate King Henry VIII.",
    release_date: "2008-02-28",
    average_rating: 6.6,
    type: "movie",
    id: 12184,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/xGrKS601NXswR0P5MpJ0EWplOEl.jpg",
    title: "The Black Dahlia",
    character: "Kay Lake",
    overview:
      "Lee Blanchard and Bucky Bleichert are former boxers-turned-cops in 1940s Los Angeles and, when an aspiring young actress turns up dead, Blanchard and Bleichert must grapple with corruption, narcissism, stag films and family madness as they pursue the killer.",
    release_date: "2006-09-15",
    average_rating: 5.7,
    type: "movie",
    id: 9676,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/7HoqdnUpIcK1CnFDNNONPZ9PBoi.jpg",
    title: "A Love Song for Bobby Long",
    character: "Pursy Will",
    overview:
      "A headstrong young woman returns to New Orleans after the death of her estranged mother.",
    release_date: "2004-09-02",
    average_rating: 6.8,
    type: "movie",
    id: 9953,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/kxWy4ffQk1FyOdo6OX7yrAJRYbm.jpg",
    title: "A Good Woman",
    character: "Meg Windermere",
    overview:
      "Fleeing 1930s New York and leaving behind a chequered past, the giltzy divorcee Mrs Stella Erlynne travels to Italy's sun-dappled Amalfi coast. Mrs Erlynne's appearance causes a stir amongst the visiting aristocracy. Based on the Oscar Wilde play \"Lady Windemere's Fan.\"",
    release_date: "2004-09-15",
    average_rating: 6.2,
    type: "movie",
    id: 15184,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dcOvIqdsojUdAtWt1nPT9xS76Su.jpg",
    title: "We Bought a Zoo",
    character: "Kelly Foster",
    overview:
      "Benjamin has lost his wife and, in a bid to start his life over, purchases a large house that has a zoo – welcome news for his daughter, but his son is not happy about it. The zoo is in need of renovation and Benjamin sets about the work with the head keeper and the rest of the staff, but, the zoo soon runs into financial trouble.",
    release_date: "2011-12-08",
    average_rating: 6.7,
    type: "movie",
    id: 74465,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
    title: "Captain America: The Winter Soldier",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.",
    release_date: "2014-03-20",
    average_rating: 7.7,
    type: "movie",
    id: 100402,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/yk4J4aewWYNiBhD49WD7UaBBn37.jpg",
    title: "Her",
    character: "Samantha (voice)",
    overview:
      "In the not so distant future, Theodore, a lonely writer purchases a newly developed operating system designed to meet the user's every needs. To Theodore's surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.",
    release_date: "2013-12-18",
    average_rating: 7.9,
    type: "movie",
    id: 152601,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/uh8bwvgGXeUKzdL4oSul9zxyTcd.jpg",
    title: "Don Jon",
    character: "Barbara Sugarman",
    overview:
      "A New Jersey guy dedicated to his family, friends, and church, develops unrealistic expectations from watching porn and works to find happiness and intimacy with his potential true love.",
    release_date: "2013-09-12",
    average_rating: 6,
    type: "movie",
    id: 138697,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/vHjEVTD8ucuwKSFOZJeyAnTZYli.jpg",
    title: "Match Point",
    character: "Nola Rice",
    overview:
      "Match Point is Woody Allen’s satire of the British High Society and the ambition of a young tennis instructor to enter into it. Yet when he must decide between two women - one assuring him his place in high society, and the other that would take him far from it - palms start to sweat and a dark psychological match in his head begins.",
    release_date: "2005-10-26",
    average_rating: 7.3,
    type: "movie",
    id: 116,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/8FHwX3beVvRJQsEa2yLhp7vy5bQ.jpg",
    title: "Deep Down",
    character: "Female Narrator (voice)",
    overview:
      "Deep Down redraws a descent into hell of a stripper called America, lost in the very depths of the U.S, taken away by a devastating love-story.",
    release_date: "2014-07-05",
    average_rating: 1,
    type: "movie",
    id: 280409,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/rJonkVkNZB23VLeoA8iGvWWZ88Z.jpg",
    title: "The Island",
    character: "Jordan Two Delta / Sarah Jordan",
    overview:
      'In 2019, Lincoln Six-Echo is a resident of a seemingly "Utopian" but contained facility. Like all of the inhabitants of this carefully-controlled environment, Lincoln hopes to be chosen to go to The Island — reportedly the last uncontaminated location on the planet. But Lincoln soon discovers that everything about his existence is a lie.',
    release_date: "2005-07-21",
    average_rating: 6.7,
    type: "movie",
    id: 1635,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/pZekG6xabTmZxjmYw10wN84Hp8d.jpg",
    title: "Marriage Story",
    character: "Nicole Barber",
    overview:
      "A stage director and an actress struggle through a grueling, coast-to-coast divorce that pushes them to their personal extremes.",
    release_date: "2019-09-28",
    average_rating: 7.8,
    type: "movie",
    id: 492188,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/AcUEhYJUKtyLdxwFJBl9QlZOprq.jpg",
    title: "Marriage Story: From the Pages to the Performances",
    character: "Herself",
    overview:
      "Join Oscar nominated filmmaker Noah Baumbach, and Oscar nominees Scarlett Johansson, Adam Driver and Laura Dern, as we take an intimate look at bringing the pages of Marriage Story to life.",
    release_date: "2019-08-29",
    average_rating: 7.6,
    type: "movie",
    id: 668735,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/83c5qOoejiurSlRSFVWWJDYmRh9.jpg",
    title: "Bride",
    character: "",
    overview:
      "A woman created to be an ideal wife— the singular obsession of a brilliant entrepreneur— rejects her creator, and is forced to flee her confined existence, confronting a world that sees her as a monster. It is on the run that she finds her true identity, her surprising power, and the strength to remake herself as her own creation.",
    release_date: "",
    average_rating: 0,
    type: "movie",
    id: 756394,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/gt51gy8deecziONPNRiSJ9tKaPo.jpg",
    title: "Jeff Koons",
    character: "Narrator (voice)",
    overview:
      "Jeff Koons is a MOCA commissioned mini-documentary on the career of artist Jeff Koons, directed by Oscar Boyson.",
    release_date: "2017-06-12",
    average_rating: 0,
    type: "movie",
    id: 776767,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/bQutrYKUprFrZlVMSRwJJQ7BCFL.jpg",
    title: "Little Shop of Horrors",
    character: "Audrey Fulquard",
    overview:
      "An exotic plant in a downtown flower shop convinces the storekeeper's meek apprentice to resort to gruesome measures to keep it alive and make it grow.",
    release_date: "",
    average_rating: 0,
    type: "movie",
    id: 346696,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/jCrjrwVkHgdIYVFdKaGLAWZKbd8.jpg",
    title: "Tower of Terror",
    character: "",
    overview: "Film adaptation of the attraction from Disney theme parks.",
    release_date: "",
    average_rating: 0,
    type: "movie",
    id: 844166,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/aHvZYoQNRTMrfs46pj64b9GrbaK.jpg",
    title: "Scoop",
    character: "Sondra Pransky",
    overview:
      "An American journalism student in London scoops a big story, and begins an affair with an aristocrat as the incident unfurls.",
    release_date: "2006-07-27",
    average_rating: 6.6,
    type: "movie",
    id: 512,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/uwKqnUPE4dSM0kKuMW0vXpURh2T.jpg",
    title: "Ghost World",
    character: "Rebecca",
    overview:
      "Two quirky, cynical teenaged girls try to figure out what to do with their lives after high school graduation. After they play a prank on an eccentric, middle aged record collector, one of them befriends him, which causes a rift in the girls' friendship.",
    release_date: "2001-07-20",
    average_rating: 7.2,
    type: "movie",
    id: 1548,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/xflTliVBvCztaLzTJx9luHnSqwD.jpg",
    title: "The Perfect Score",
    character: "Francesca Curtis",
    overview:
      "Six high school seniors decide to break into the Princeton Testing Center so they can steal the answers to their upcoming SAT tests and all get perfect scores.",
    release_date: "2004-01-30",
    average_rating: 5.7,
    type: "movie",
    id: 13505,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/5MTZwe8XyvFdJjgP93sb7HGraJO.jpg",
    title: "Woody Allen: A Documentary",
    character: "Herself",
    overview:
      "Iconic writer, director, actor, comedian and musician Woody Allen allowed his life and creative process to be documented on-camera for the first time. With this unprecedented access, Emmy-winning, Oscar-nominated filmmaker Robert B. Weide followed the notoriously private film legend over a year and a half to create the ultimate film biography. \"Woody Allen: A Documentary\" chronicles Allen's career - from teen writer to Sid Caesar's TV scribe, from stand-up comedian to award-winning writer-director averaging one film-per-year for more than 40 years. Exploring Allen's writing habits, casting, directing, and relationship with his actors first-hand, new interviews with A-listers, writing partners, family and friends provide insight and backstory to the usually inscrutable filmmaker.",
    release_date: "2011-11-20",
    average_rating: 6.9,
    type: "movie",
    id: 81167,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/zlG4QzB00VM6QHUmRkKaboCOgat.jpg",
    title: "Hitchcock",
    character: "Janet Leigh",
    overview:
      "Follow the relationship between director Alfred Hitchcock and his wife Alma Reville during the making of his most famous horror-thriller film, Psycho, and the trials and tribulations the director faced from Hollywood censors.",
    release_date: "2012-11-22",
    average_rating: 6.5,
    type: "movie",
    id: 112336,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/41Ke02UzYoPsiTc3YbomPGiQKMl.jpg",
    title: "Marvel Studios: Assembling a Universe",
    character: "Self",
    overview:
      'A look at the story behind Marvel Studios and the Marvel Cinematic Universe, featuring interviews and behind-the-scenes footage from all of the Marvel films, the Marvel One-Shots and "Marvel\'s Agents of S.H.I.E.L.D."',
    release_date: "2014-03-18",
    average_rating: 7,
    type: "movie",
    id: 259910,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
    title: "Captain America: Civil War",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
    release_date: "2016-04-27",
    average_rating: 7.4,
    type: "movie",
    id: 271110,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
    title: "Jojo Rabbit",
    character: "Rosie Betzler",
    overview:
      "A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.",
    release_date: "2019-10-18",
    average_rating: 8.1,
    type: "movie",
    id: 515001,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/eAeD5AOAbKCFkQgejxGbzOIVNB6.jpg",
    title: "Sing 2",
    character: "Ash (voice)",
    overview:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    release_date: "2021-12-02",
    average_rating: 0,
    type: "movie",
    id: 438695,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/97kLtkSnVMhwgoCS020h4CERj7m.jpg",
    title: "VOMO: Vote or Miss Out",
    character: "Self",
    overview:
      "Some of the biggest names in comedy and music come together for a nonpartisan comedy special event to provide information on voting so that every voter has the knowledge and incentive to participate in the 2020 fall US election.",
    release_date: "2020-09-14",
    average_rating: 10,
    type: "movie",
    id: 740422,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Moneymaker: Behind the Black Widow",
    character: "Narrator (voice)",
    overview:
      "Heidi Moneymaker has been part of the Marvel Cinematic Universe for over a decade. Witness her in action when the highly-anticipated Marvel Studios' film Black Widow",
    release_date: "2021-07-05",
    average_rating: 0,
    type: "movie",
    id: 847953,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/1Ptdh2fdA5xpH5Zj8AQUAp9Tdoa.jpg",
    title: "The Horse Whisperer",
    character: "Grace MacLean",
    overview:
      "Based on the novel by the same name from Nicholas Evans, the talented Robert Redford presents this meditative family drama set in the country side. Redford not only directs but also stars in the roll of a cowboy with a magical talent for healing.",
    release_date: "1998-05-14",
    average_rating: 6.9,
    type: "movie",
    id: 547,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/gcphM7ZLxS5HPeCZgjZobfz907x.jpg",
    title: "The Prestige",
    character: "Olivia Wenscombe",
    overview:
      "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
    release_date: "2006-10-19",
    average_rating: 8.2,
    type: "movie",
    id: 1124,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/ruc33YnCrmCL8PHdPQVzfa4shWX.jpg",
    title: "He's Just Not That Into You",
    character: "Anna Marks",
    overview:
      "Remember that really cute girl/guy who said they'd call – and didn't? Maybe they lost your number. Maybe they're in the hospital. Maybe they're awed by your looks, brains or success. Or maybe... They're just not that into you.",
    release_date: "2009-02-06",
    average_rating: 6.5,
    type: "movie",
    id: 10184,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/1hf7x6WmyXtL1MlY4eSlTbZ8Nzu.jpg",
    title: "Eight Legged Freaks",
    character: "Ashley Parker",
    overview:
      "The residents of a rural mining town discover that an unfortunate chemical spill has caused hundreds of little spiders to mutate overnight to the size of SUVs. It's then up to mining engineer Chris McCormack and Sheriff Sam Parker to mobilize an eclectic group of townspeople, including the Sheriff's young son, Mike, her daughter, Ashley, and paranoid radio announcer Harlan, into battle against the bloodthirsty eight-legged beasts.",
    release_date: "2002-07-17",
    average_rating: 5.7,
    type: "movie",
    id: 8869,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "On the Front Line",
    character: "Self",
    overview:
      "An inside look at Captain America's Battlegrounds, the stunt choreography behind the The Winter Soldier",
    release_date: "2014-09-09",
    average_rating: 7.9,
    type: "movie",
    id: 291718,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/qNC8co8LuGBv22Fu9SC71ppAwoA.jpg",
    title: "Marvel: 75 Years, From Pulp to Pop!",
    character: "Herself",
    overview:
      "In celebration of the publisher's 75th anniversary, the hour-long special will take a detailed look at the company's journey from fledgling comics publisher to multi-media juggernaut. Hosted by Emily VanCamp (S.H.I.E.L.D. Agent Sharon Carter), the documentary-style feature will include interviews with comic book icons, pop culture authorities, and Hollywood stars.  The special also promises an \"extraordinary peek into Marvel's future!\" Might Marvel release the first official footage from next year's Avengers: Age of Ultron or Ant-Man? If they do, you'll know about it here.",
    release_date: "2014-11-04",
    average_rating: 6.9,
    type: "movie",
    id: 299969,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
    title: "Iron Man 2",
    character: "Natalie Rushman / Natasha Romanoff / Black Widow",
    overview:
      "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
    release_date: "2010-04-28",
    average_rating: 6.8,
    type: "movie",
    id: 10138,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/lW0kUtXTOVlHTVhDO2VzNBACAHX.jpg",
    title: "Sing",
    character: "Ash (voice)",
    overview:
      "A koala named Buster recruits his best friend to help him drum up business for his theater by hosting a singing competition.",
    release_date: "2016-11-23",
    average_rating: 7.1,
    type: "movie",
    id: 335797,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Art as Dialogue",
    character: "Herself",
    overview: "Documentary on acting in the movie Ghost World (2001).",
    release_date: "2017-05-30",
    average_rating: 6,
    type: "movie",
    id: 541234,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/3TKR326AjEOtizPqfiKdEeb6IrR.jpg",
    title: "Chadwick Boseman:  A Tribute for a King",
    character: 'Self - Actress, "Avengers: Endgame"',
    overview: "A tribute to Chadwick Boseman, celebrating his life and legacy.",
    release_date: "2020-08-30",
    average_rating: 8.3,
    type: "movie",
    id: 738005,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/lrCgt8NNMyFsfmXyXiSSCRXNH4u.jpg",
    title: "The Man Who Wasn't There",
    character: "Birdy Abundas",
    overview:
      "A tale of murder, crime and punishment set in the summer of 1949. Ed Crane, a barber in a small California town, is dissatisfied with his life, but his wife Doris' infidelity and a mysterious opportunity presents him with a chance to change it.",
    release_date: "2001-10-26",
    average_rating: 7.6,
    type: "movie",
    id: 10778,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    title: "The Avengers",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
    release_date: "2012-04-25",
    average_rating: 7.7,
    type: "movie",
    id: 24428,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
    title: "Avengers: Age of Ultron",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
    release_date: "2015-04-22",
    average_rating: 7.3,
    type: "movie",
    id: 99861,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Lost on Location: Behind the Scenes of 'Lost in Translation'",
    character: "Herself",
    overview:
      "Behind the scenes documentary shot during the making of Sofia Coppola's Lost In Translation (2003)",
    release_date: "2004-02-03",
    average_rating: 7.5,
    type: "movie",
    id: 113149,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/yMtKHR6VG1Yagvv5F7IFpsGBm66.jpg",
    title: "Chef",
    character: "Molly",
    overview:
      "When Chef Carl Casper suddenly quits his job at a prominent Los Angeles restaurant after refusing to compromise his creative integrity for its controlling owner, he is left to figure out what's next. Finding himself in Miami, he teams up with his ex-wife, his friend and his son to launch a food truck. Taking to the road, Chef Carl goes back to his roots to reignite his passion for the kitchen -- and zest for life and love.",
    release_date: "2014-05-08",
    average_rating: 7.1,
    type: "movie",
    id: 212778,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/tOEOlmLP71IojeJ91dyJ9Nsb8O8.jpg",
    title: "The Jungle Book",
    character: "Kaa (voice)",
    overview:
      "A man-cub named Mowgli fostered by wolves. After a threat from the tiger Shere Khan, Mowgli is forced to flee the jungle, by which he embarks on a journey of self discovery with the help of the panther, Bagheera and the free-spirited bear, Baloo.",
    release_date: "2016-04-07",
    average_rating: 6.9,
    type: "movie",
    id: 278927,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Yes We Can",
    character: "Herself",
    overview:
      "Yes We Can (2008)  Video 5 min  -  Short | Music  -  2 February 2008 (USA)",
    release_date: "2008-02-02",
    average_rating: 8.5,
    type: "movie",
    id: 280417,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Translating History to Screen",
    character: "Herself",
    overview:
      "Translating History to Screen (2008)  Video Short  -  10 June 2008 (USA)",
    release_date: "2008-06-10",
    average_rating: 2,
    type: "movie",
    id: 280419,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/txvoksUbyxqvaOvDfEbwW5nEcmX.jpg",
    title: "Hail, Caesar!",
    character: "DeeAnna Moran",
    overview:
      "When a Hollywood star mysteriously disappears in the middle of filming, the studio sends their fixer to get him back.",
    release_date: "2016-02-05",
    average_rating: 5.9,
    type: "movie",
    id: 270487,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    title: "Avengers: Infinity War",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    release_date: "2018-04-25",
    average_rating: 8.3,
    type: "movie",
    id: 299536,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/2kBT7KONKQTIhkMc2ZtPU11E8Ky.jpg",
    title: "The Avengers: A Visual Journey",
    character: "Herself",
    overview:
      "Joss Whedon and others in interviews discussing the aims for this new franchise.",
    release_date: "2012-09-25",
    average_rating: 8.4,
    type: "movie",
    id: 448368,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    title: "Avengers: Endgame",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    release_date: "2019-04-24",
    average_rating: 8.3,
    type: "movie",
    id: 299534,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "The Prestige: Now That's Magic",
    character: "Self",
    overview: "Featurette on the making of The Prestige (2006).",
    release_date: "2006-11-11",
    average_rating: 0,
    type: "movie",
    id: 703398,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/6sgo6TCakeL4KFwwcJyvkZ7zhMX.jpg",
    title: "The SpongeBob SquarePants Movie",
    character: "Princess Mindy (voice)",
    overview:
      "There's trouble brewing in Bikini Bottom. Someone has stolen King Neptune's crown, and it looks like Mr. Krab, SpongeBob's boss, is the culprit. Though he's just been passed over for the promotion of his dreams, SpongeBob stands by his boss, and along with his best pal Patrick, sets out on a treacherous mission to Shell City to reclaim the crown and save Mr. Krab's life.",
    release_date: "2004-11-14",
    average_rating: 6.9,
    type: "movie",
    id: 11836,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/z8WqDIUC00TPX6U24ah0C7IMEKf.jpg",
    title: "Just Cause",
    character: "Kate Armstrong",
    overview:
      "A Harvard professor is lured back into the courtroom after twenty-five years to take the case of a young black man condemned to death for the horrific murder of a child.",
    release_date: "1995-02-17",
    average_rating: 6.2,
    type: "movie",
    id: 9061,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dM89Q3kB0ye7m3UB2WV50n3mMm1.jpg",
    title: "Marvel Studios: The First Ten Years - The Evolution of Heroes",
    character: "Self",
    overview:
      "A discussion of several key MCU characters -- Iron Man, Thor, Captain America -- as well as their work together in the Avengers films, other recent MCU entries, and the upcoming Infinity War.",
    release_date: "2018-03-06",
    average_rating: 7.1,
    type: "movie",
    id: 638399,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/ig5LhLEnlt7QCyYjgui082fO4ih.jpg",
    title: "If Lucy Fell",
    character: "Emily",
    overview:
      "Joe and Lucy are roommates and best friends. Lucy, whose love life is embarrassingly dull, convinces Joe, who is infatuated with a neighbor he's never met, that if they don't have stable romances within a month, they must jump off the Brooklyn Bridge.",
    release_date: "1996-03-08",
    average_rating: 5.3,
    type: "movie",
    id: 10324,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/4nRzyiVckWoqE9Vpm35yZTrfkJM.jpg",
    title: "Fall",
    character: "Little Girl",
    overview:
      "For Michael Shiver, life as an easy-going cab driver in New York suddenly changes when he picks up supermodel Sarah Easton and falls head over heels in love. But Sarah has more than just passion on her mind; she also has a husband and a glamorous lifestyle that she can't seem to leave behind. Torn between her feelings for Michael and the security of her marriage, Sarah is forced to make a realistic decision about the sacrifices that must be made to be truly and totally in love.",
    release_date: "1997-06-20",
    average_rating: 7.1,
    type: "movie",
    id: 37567,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/coS6rIaucxDzq20kiJozTgQ0Nmk.jpg",
    title: "Building the Dream: Assembling the Avengers",
    character: "Herself",
    overview:
      "Witness Marvel's epic journey, from its comic book origins to its blockbuster film franchises, through seven exclusive featurettes. Get the inside story, with exclusive behind-the-scenes footage and cast interviews, and discover the history behind its legendary characters and films -- Iron Man, The Incredible Hulk, Iron Man 2, Thor, Captain America: The First Avenger, and Marvel's The Avengers! With over 90 minutes of original footage, this is your all-access pass to Marvel and Phase One of the Marvel Cinematic Universe!",
    release_date: "2012-09-25",
    average_rating: 8.6,
    type: "movie",
    id: 448366,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/6uOadrCfle0n2LOOxHbgWEdnrm2.jpg",
    title: "Home Alone 3",
    character: "Molly Pruitt",
    overview:
      "9-year-old Alex Pruitt is home alone with the chicken pox. Turns out, due to a mix-up among nefarious spies, Alex was given a toy car concealing a top-secret microchip. Now Alex must fend off the spies as they try break into his house to get it back.",
    release_date: "1997-12-12",
    average_rating: 5.3,
    type: "movie",
    id: 9714,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/uF8uAzu8aMQwAGFOPNhLeFzsOhh.jpg",
    title: "Bert Stern: Original Madman",
    character: "Herself (archive footage)",
    overview:
      "The untold and intimate life story of one of the greatest American photographers of all time, Bert Stern. After working alongside Stanley Kubrick at Look Magazine, Stern became an original Madison Avenue 'mad man', his images helping to create modern advertising. Ground-breaking photos of Elizabeth Taylor and Richard Burton, Marilyn Monroe and Twiggy, coupled with his astonishing success in advertising, minted Stern as a celebrity in his own right.",
    release_date: "2011-09-02",
    average_rating: 8,
    type: "movie",
    id: 94026,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/wAOJ0PmoRmHL5vXG0KCUrtDWm6q.jpg",
    title: "Floyd Norman: An Animated Life",
    character: "Herself",
    overview:
      'Animator. Storyman. Troublemaker. At 80 years old, see how Disney Legend Floyd Norman, the first African-American animator at Disney, continues to impact animation and stir up "trouble" after the company forced him to retire at age 65.',
    release_date: "2016-02-05",
    average_rating: 7,
    type: "movie",
    id: 407588,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/c0nUX6Q1ZB0P2t1Jo6EeFSVnOGQ.jpg",
    title: "Isle of Dogs",
    character: "Nutmeg (voice)",
    overview:
      "In the future, an outbreak of canine flu leads the mayor of a Japanese city to banish all dogs to an island that's a garbage dump. The outcasts must soon embark on an epic journey when a 12-year-old boy arrives on the island to find his beloved pet.",
    release_date: "2018-03-23",
    average_rating: 7.9,
    type: "movie",
    id: 399174,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/e4JEG7dstmurXMUPOW9Jy6UDR9F.jpg",
    title: "North",
    character: "Laura Nelson",
    overview:
      "Eleven-year-old North has had it with his parents. They are always busy with their careers and don't give North the attention he needs, so he files a lawsuit against them. The judge rules that North should either find new parents or return to his own parents within two months. Thus North starts off on a journey around the world to find parents that really care about him.",
    release_date: "1994-07-22",
    average_rating: 5,
    type: "movie",
    id: 31586,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/8qlFNCxQQOLfnqwRcHY6WMkb7tF.jpg",
    title: "Celebrating Marvel's Stan Lee",
    character: "Natasha Romanoff / Black Widow (archive footage)",
    overview:
      "A special aired on ABC to look back on the historic career of the one and only Stan Lee.",
    release_date: "2019-12-20",
    average_rating: 9.8,
    type: "movie",
    id: 662151,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/iRQnmVnjugeM54SNGMAD6idhRlb.jpg",
    title: "Saturday Night Live: The Best of Amy Poehler",
    character: "Herself (archive footage)",
    overview:
      "Amy Poehler's best Saturday Night Live sketches and performances.",
    release_date: "2009-04-18",
    average_rating: 8.2,
    type: "movie",
    id: 325384,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/1xJNi6ljfFFWeLmDI5DFslLq7L2.jpg",
    title:
      "United We Stand, Divided We Fall: The Making of 'Captain America: Civil War'",
    character: "",
    overview:
      "A two part feature. Part 1 (22:25) features cast and crew looking back at the story's comic book origins and discussing the story's thematic depth and relevance, the large assortment of characters featured in the film, the directors' contributions, the casts' abilities to perform complex stunt work, making various scenes, character relationships and development in the film, shooting locations, key props, Ant-Man's role in the film, choosing which characters would side with which faction, and General Ross' part in the movie. Part 2 (23:18) begins with a discussion of Vision's role in the film and Paul Bettany's performance, the part Black Panther plays in the movie and Chadwick Boseman's work on the film, Tom Holland's performance and Spider-Man's part in the story, making the large-scale battle between the warring factions, the villain Zemo, a major revelation in the film, and more.",
    release_date: "2016-09-13",
    average_rating: 7.4,
    type: "movie",
    id: 448378,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
    title: "Captain Marvel",
    character: "Natasha Romanoff / Black Widow (uncredited)",
    overview:
      "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
    release_date: "2019-03-06",
    average_rating: 6.9,
    type: "movie",
    id: 299537,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    title: "Thor: Ragnarok",
    character: "Natasha Romanoff / Black Widow (archive footage / uncredited)",
    overview:
      "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
    release_date: "2017-10-25",
    average_rating: 7.6,
    type: "movie",
    id: 284053,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Close Up",
    character: "Herself",
    overview: "",
    average_rating: 0,
    type: "tv",
    id: 18908,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/rHHSx7kyLEHK48Y3LO3sNfclOT2.jpg",
    title: "The Rosie O'Donnell Show",
    character: "",
    overview:
      "The Rosie O'Donnell Show was an American daytime television talk show hosted and produced by actress and comedian Rosie O'Donnell. It aired for six seasons from 1996 to 2002. Topics often discussed on the show include Broadway, children, extended families and charitable works, people and organizations.\n\nThe show was based out of Studio 8G at NBC's Rockefeller Center studios in New York City, NY, USA and was produced and syndicated by KidRo Productions, Telepictures Productions and Warner Bros. Television.",
    average_rating: 3,
    type: "tv",
    id: 1503,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/4DfhmpxL3jMqpuZFU1kBoNy364o.jpg",
    title: "CBS News Sunday Morning",
    character: "Herself",
    overview:
      "The sparkling notes of a trumpet fanfare and the familiar logo of the sun alert viewers that it's time for CBS's Sunday morning staple. Journalist Jane Pauley helms the show, taking over hosting duties from Charles Osgood, who spent 22 years on the job. A morning talk show, this program airs at a different pace and focuses much of its attention on the performing arts. After a quick update of the day's news and national weather, correspondents offer longer-length segments on a variety of topics, from architecture to ballet to music to pop culture to politics.",
    average_rating: 6.9,
    type: "tv",
    id: 4026,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/nz5fAg1OomLZ7fxiM4RnLbJxppc.jpg",
    title: "The Daily Show with Trevor Noah",
    character: "Herself",
    overview:
      "Trevor Noah and The World's Fakest News Team tackle the biggest stories in news, politics and pop culture.",
    average_rating: 6.4,
    type: "tv",
    id: 2224,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/cGFOMyTM4DRXeBVCRUV8EGnJ8iq.jpg",
    title: "The Queen Latifah Show",
    character: "Herself",
    overview:
      "The Queen Latifah Show is an American talk-variety series hosted by Queen Latifah that premiered on September 16, 2013. Previously, a talk show with the exact same title had aired from 1999 to 2001. However the current show is not a revival of this older syndicated television production.\n\nThe Queen Latifah Show features celebrity interviews, human interest stories, musical performances and Queen Latifah's take on pop culture news. Queen Latifah also ventures into communities across the country to share compelling stories, celebrate individuals who give back to their communities and delivers life-changing surprises. The series is produced by Flavor Unit Entertainment, Overbrook Entertainment, and Sony Pictures Television.",
    average_rating: 3.5,
    type: "tv",
    id: 13992,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Made in Hollywood",
    character: "Herself",
    overview:
      "Made in Hollywood is a talk show hosted by Kylie Erica Mar and Julie L. Harkness airing in syndication since September 30, 2005. The series is currently in its seventh season. The series is filmed in two studios in Los Angeles, California and New York City. Made in Hollywood also airs a spinoff series, Made in Hollywood: Teen Edition.",
    average_rating: 1,
    type: "tv",
    id: 41559,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/iJvwr7kL0Q7BtrYC38KQ5baPw7g.jpg",
    title: "The Early Show",
    character: "Herself",
    overview:
      "The Early Show is an American morning television show which was broadcast by CBS from New York City from 1999 to 2012. The program aired live from 7 to 9 a.m. Eastern Time Monday through Friday in the Eastern time zone; most affiliates in the Central, Mountain, and Pacific time zones aired the show on tape-delay from 7 to 9 a.m. local time. The Saturday edition aired live from 7 to 9 a.m. Eastern Time as well, but a number of affiliates did not carry it or aired it later on tape-delay. It premiered on November 1, 1999, and was the newest of the major networks' morning shows, although CBS has made several attempts to program in the morning slot since 1954. The show aired as a division of CBS News.\n\nThe Early Show, like many of its predecessors, traditionally ran last in the ratings to its rivals, NBC's Today and ABC's Good Morning America. Much like NBC's The Today Show and The Tonight Show, the title The Early Show was analogous to that of CBS's late-night talk show, The Late Show.\n\nOn November 15, 2011, CBS announced that a new morning show would replace The Early Show on January 9, 2012. CBS News chairman Jeff Fager and CBS News president David Rhodes stated that the new show would \"redefine the morning television landscape.\" On December 1, it was announced that the new show would be titled CBS This Morning. The Early Show ended its twelve-year run on January 6, 2012, to make way for the program. Charlie Rose, Gayle King, and Erica Hill were named anchors of the new program.",
    average_rating: 5,
    type: "tv",
    id: 3167,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Showbiz Tonight",
    character: "Herself",
    overview:
      "Showbiz Tonight is an American entertainment news program on HLN.\n\nShowbiz Tonight is hosted by A.J. Hammer at CNN New York. The show reports and debates celebrity entertainment news stories and controversies, along with social networking segments involving viewer interaction via social networks and the program's call-in toll free number. The program airs Monday through Thursday nights at 11 p.m. Eastern, with encore presentations on Tuesday through Saturday mornings at 2 a.m. and 4:10 a.m. Eastern. Showbiz Tonight is also shown several times daily in Europe on Star! Scandinavia, a channel operated by Turner NonStop Television, part of Turner Broadcasting.",
    average_rating: 1,
    type: "tv",
    id: 5206,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Silenci?",
    character: "Herself",
    overview: "",
    average_rating: 10,
    type: "tv",
    id: 37439,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/n2PHBbRwNxaQGuqIW4Y5ulq0HQC.jpg",
    title: "American Masters",
    character: "Herself",
    overview:
      "American Masters is a PBS television series which produces biographies on enduring writers, musicians, visual and performing artists, dramatists, filmmakers, and others who have left an indelible impression on the cultural landscape of the United States.",
    average_rating: 8,
    type: "tv",
    id: 15069,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Cartelera",
    character: "Herself",
    overview: "Cartelera (1994–2008)\r\n\r\nTV Series  -  30 min",
    average_rating: 0,
    type: "tv",
    id: 60975,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Made in Hollywood: Teen Edition",
    character: "Herself",
    overview:
      "Made in Hollywood: Teen Edition is a spinoff series of Made in Hollywood, hosted by Kylie Erica Mar. Guests stars featured on the show include Daniel Radcliffe and Jennifer Aniston. Since the show is targeted to ages 13 to 16, and it is educational, it meets the standards for the FCC's E/I guidelines.",
    average_rating: 0,
    type: "tv",
    id: 41432,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/ukcq1C41ckPwpRuU0tI7Mo6oR1p.jpg",
    title: "Días de cine",
    character: "Herself",
    overview:
      "Antonio Gasset hosts this show in which recently released movies and DVDs are thoughtfully discussed, in a documentary-like way.",
    average_rating: 8.8,
    type: "tv",
    id: 48460,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/w4QoW2O4djVPwiRLN7TPvfxf5jl.jpg",
    title: "Stand Up to Cancer",
    character: "Herself",
    overview:
      "A biennial charitable telethon bringing together all the networks and the biggest stars in entertainment, for one night of music, laughter, and inspiration. The aim is to raise significant funds for translational cancer research, raise awareness, and bring about an understanding that everyone is connected to cancer.",
    average_rating: 8.5,
    type: "tv",
    id: 39990,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Cinema 3",
    character: "Herself",
    overview: "",
    average_rating: 0,
    type: "tv",
    id: 39442,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Up Close with Carrie Keagan",
    character: "Herself",
    overview: "",
    average_rating: 10,
    type: "tv",
    id: 39451,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/siVOE6ZYzFQfVY7j0hakoqzr8Yf.jpg",
    title: "Entourage",
    character: "Herself",
    overview:
      "Film star Vince Chase navigates the vapid terrain of Los Angeles with a close circle of friends and his trusty agent.",
    average_rating: 7.3,
    type: "tv",
    id: 1940,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/9sChks5yBfeOBloOVGXIc7QFQ0p.jpg",
    title: "The Sharon Osbourne Show",
    character: "Herself",
    overview:
      "The Sharon Osbourne Show refers to either of two TV chat shows hosted by Sharon Osbourne – the original US version, or the more recent UK version. These are described separately below.",
    average_rating: 0,
    type: "tv",
    id: 2478,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Teen Choice Awards",
    character: "Herself",
    overview:
      "The Teen Choice Awards is a teen awards show presented annually by Fox. The first awards were held in 1999. The program honors the year's biggest achievements in music, movies, sports, television, fashion and more, as voted on by teens aged 13–19. The program features a number of celebrities and also musical performers. The winners are awarded with authentic mini size (182 cm) surfboards designed with a summertime theme. The ceremony has created spin-off teen awards on YouTube.",
    average_rating: 10,
    type: "tv",
    id: 43117,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/hs35wiiaNq34wvo4wd9xByKDcHH.jpg",
    title: "Jimmy Kimmel Live!",
    character: "Herself",
    overview:
      "Jimmy Kimmel Live! is an American late-night talk show, created and hosted by Jimmy Kimmel and broadcast on ABC.",
    average_rating: 5.4,
    type: "tv",
    id: 1489,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/jrGlKiEMROImZWZTD38JO4D420.jpg",
    title: "Biography",
    character: "Herself",
    overview:
      "Biography is a documentary television series. It was originally a half-hour filmed series produced for CBS by David Wolper from 1961 to 1964 and hosted by Mike Wallace. The A&E Network later re-ran it and has produced new episodes since 1987. The older version featured historical figures such as Helen Keller and Mark Twain, or long-dead entertainment figures such as Will Rogers or John Barrymore. The A&E series has placed the emphasis on such people as Marilyn Monroe, Elvis Presley, Plácido Domingo, Freddie Mercury, Jacqueline Kennedy Onassis, Eric Clapton, Pope John Paul II, Gene Tierney, Selena, Diego Rivera, Mao Zedong and Queen Elizabeth II, and fictional characters like The Phantom, Superman, Hamlet, Betty Boop, and Santa Claus. The program ended up profiling enough figures that in 1999, A&E spun it off into an entire network, The Biography Channel.",
    average_rating: 6.1,
    type: "tv",
    id: 4994,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/mdhit408BYXjSw8VvhHnmXLPAmS.jpg",
    title: "Good Day L.A.",
    character: "Herself",
    overview:
      "Good Day L.A. is a morning talk show airing on KTTV, the Fox Broadcasting Company-owned and operated station in Los Angeles, California. The show airs Monday through Friday mornings from 7:00 AM to 10:00 AM and is simulcast live on myfoxla.com. The show is currently hosted by Steve Edwards and co-hosted by Maria Sansone, with Maria Quiban doing weather and social media reports, Julie Chang covering entertainment, and Rick Dickert covering traffic reports.",
    average_rating: 0,
    type: "tv",
    id: 12296,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
    title: "LIVE with Kelly and Ryan",
    character: "Herself",
    overview:
      "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
    average_rating: 5.4,
    type: "tv",
    id: 1900,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Guys Choice Awards",
    character: "Herself",
    overview:
      "The Spike Guys' Choice Awards is an awards show produced by the Viacom cable channel Spike and held since 2007. It is patterned after Viacom's MTV Movie Awards. The winners are chosen based on voting by fans and viewers of the channel.\n\nThe trophy for the award is a golden pair of antlers on a wooden pedestal, which is to symbolize the stag which is often associated with masculinity.",
    average_rating: 0,
    type: "tv",
    id: 14498,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "omg! Insider",
    character: "Herself",
    overview:
      'omg! Insider is an American entertainment news program covering events and celebrities. It debuted on September 13, 2004 as a spinoff of Entertainment Tonight and started as a popular segment that took viewers "behind closed doors" and gave them "inside" information. Since becoming a separate program, it took a tabloid direction, and has gone through several formats since its 2004 premiere, though since the start of the 2011-12 season it has lost many of the tabloid elements and become more of a straight rundown of entertainment news.\n\nThe original theme song was performed by Richie Sambora.\n\nOn January 7, 2013, The Insider changed its name to omg! Insider.',
    average_rating: 1.5,
    type: "tv",
    id: 3699,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "The Client",
    character: "Jenna Halliwell",
    overview:
      "The Client is an American television series that aired on CBS from September 18, 1995 to August 16, 1996. The series was based on the 1994 film The Client, itself adapted from the 1993 John Grisham novel also of the same name.",
    average_rating: 6,
    type: "tv",
    id: 29600,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/xLrZii9InlGrl238QaKzm90E1WB.jpg",
    title: "Brit Awards",
    character: "Herself",
    overview: "",
    average_rating: 0,
    type: "tv",
    id: 45873,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/gJZ1rhLLFpatuAeylJoUI82DKC7.jpg",
    title: "Late Night with Conan O'Brien",
    character: "Herself",
    overview:
      "Late Night with Conan O'Brien is an American late-night talk show hosted by Conan O'Brien that aired 2,725 episodes on NBC between 1993 and 2009. The show featured varied comedic material, celebrity interviews, and musical and comedy performances. Late Night aired weeknights at 12:37 am Eastern/11:37 pm Central and 12:37 am Mountain in the United States. From 1993 until 2000, Andy Richter served as O'Brien's sidekick; following his departure, O'Brien was the show's sole featured performer. The show's house musical act was The Max Weinberg 7, led by E Street Band drummer Max Weinberg.\n\nThe second incarnation of NBC's Late Night franchise, O'Brien's debuted in 1993 after David Letterman, who hosted the first incarnation of Late Night, moved to CBS to host Late Show opposite The Tonight Show. In 2004, as part of a deal to secure a new contract, NBC announced that O'Brien would leave Late Night in 2009 to succeed Jay Leno as the host of The Tonight Show. Jimmy Fallon began hosting his version of Late Night on March 2, 2009.",
    average_rating: 7.3,
    type: "tv",
    id: 4573,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/zz6DBrPThie8i99QlzWs3NNj63s.jpg",
    title: "Tony Awards",
    character: "Self",
    overview:
      "The Antoinette Perry Award for Excellence in Theatre, more commonly known as a Tony Award, recognizes achievement in live Broadway theatre. The awards are presented by the American Theatre Wing and The Broadway League at an annual ceremony in New York City. The awards are given for Broadway productions and performances, and an award is given for regional theatre.",
    average_rating: 6,
    type: "tv",
    id: 30048,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/2fABKyKKX6r4FUuCjd7qKmgNOID.jpg",
    title: "The Late Late Show with Craig Kilborn",
    character: "Herself",
    overview:
      "Craig Kilborn hosted this zany talk show, which followed David Letterman's show, from 1999 until 2004. Kilborn left The Daily Show in 1999 to be this show's host after Tom Synder retired. The segment \"5 Questions\" was carried over from when he was on The Daily Show. Kilborn was frequently beaten in the ratings by his NBC timeslot rival, Conan O'Brien. Kilborn left The Late Late Show to pursue new opportunities.",
    average_rating: 3.9,
    type: "tv",
    id: 27213,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Gomorron",
    character: "Herself",
    overview:
      "Gomorronis a Swedish morning news and talk show that airs every morning on TV4. It is similar to The Today Show. Gomorron started airing in 1992.",
    average_rating: 0,
    type: "tv",
    id: 39122,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Le Grand Journal",
    character: "Herself",
    overview:
      "Le Grand Journal is a French nightly news and talk show airing every weekday evening on Canal+. Debuting on August 30, 2004, it was created and hosted by Michel Denisot and in 2013 by Antoine de Caunes. Originally a one-hour program, it expanded to two hours in 2005. Even though the show is broadcast on the premium channel Canal+, this is an unencrypted program.\n\nThe program features news, talk, weather and comedy. The program is produced by KM Productions for Canal+ and broadcasts from the Studios Rive Gauche on Quai André-Citroën in Paris.",
    average_rating: 6,
    type: "tv",
    id: 27391,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dUarLANS82FgBOHjRnJw42FB1z4.jpg",
    title: "Saturday Night Live",
    character: "Self",
    overview:
      "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
    average_rating: 7,
    type: "tv",
    id: 1667,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/wF43fJ8D85i79ZrLZsnUZ2JurbP.jpg",
    title: "The Oscars",
    character: "Self",
    overview:
      "An annual American awards ceremony honoring cinematic achievements in the film industry. The various category winners are awarded a copy of a statuette, officially the Academy Award of Merit, that is better known by its nickname Oscar.",
    average_rating: 7,
    type: "tv",
    id: 27023,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/irA6aNsYCpN7Uo4EDQo8Fu6uzh7.jpg",
    title: "The Tonight Show with Jay Leno",
    character: "Herself",
    overview:
      "The Tonight Show with Jay Leno is an American late-night talk show hosted by Jay Leno that initially aired from May 25, 1992 to May 29, 2009, and resumed production on March 1, 2010. The fourth incarnation of the Tonight Show franchise made its debut on May 25, 1992, three days following Johnny Carson's retirement as host of the program. The program originates from NBC Studios in Burbank, California, and is broadcast Monday through Friday at 11:35 PM in the Eastern and Pacific time zones. Unlike Carson or his predecessor Jack Paar, Leno only once utilized a guest host, preferring to host the series by himself.\n\nOn April 26, 1999, the show began broadcasting in 1080i HDTV, becoming the first American nightly talk show to be shot in high definition. The show is shot in 16:9 aspect ratio.\n\nThe series, which followed the same basic format as that of his predecessors, ran until May 29, 2009, after which Leno was succeeded by Conan O'Brien. NBC signed Leno to a new deal for a nightly talk show in the 10:00 pm ET timeslot. The primetime series, titled The Jay Leno Show, debuted on September 14, 2009, following a similar format to the Leno incarnation of Tonight.",
    average_rating: 5.4,
    type: "tv",
    id: 2518,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/fNLx9eH8EwyA92K6h2Bjvm0N1cN.jpg",
    title: "Ant & Dec's Saturday Night Takeaway",
    character: "Herself",
    overview:
      "A gameshow hosted by Ant and Dec filled with stunts, sketches, and special guest appearances.",
    average_rating: 5.8,
    type: "tv",
    id: 2564,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/huOt54c3W7btagt2fRCyJ4i2ePm.jpg",
    title: "E! Live from the Red Carpet",
    character: "Herself",
    overview:
      "The pre-show to the major award shows that airs on E! Entertainment Television. Live From the Red Carpet covers celebrity arrivals and gets you right up for a first-row seat to see the stars and all the excitement with live coverage of the fashion, flair, glitz and glamour.",
    average_rating: 2.2,
    type: "tv",
    id: 14598,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/xlWdasY9oYg3OO5VTNqlPFftgya.jpg",
    title: "Today",
    character: "Herself",
    overview:
      "Today is a daily American morning television show that airs on NBC. The program debuted on January 14, 1952. It was the first of its genre on American television and in the world, and is the fifth-longest running American television series. Originally a two-hour program on weekdays, it expanded to Sundays in 1987 and Saturdays in 1992. The weekday broadcast expanded to three hours in 2000, and to four hours in 2007.\n\nToday's dominance was virtually unchallenged by the other networks until the late 1980s, when it was overtaken by ABC's Good Morning America. Today retook the Nielsen ratings lead the week of December 11, 1995, and held onto that position for 852 consecutive weeks until the week of April 9, 2012, when it was beaten by Good Morning America yet again. In 2002, Today was ranked #17 on TV Guide's 50 Greatest Television  Shows of All Time.",
    average_rating: 5.6,
    type: "tv",
    id: 1709,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Daybreak",
    character: "Herself",
    overview:
      "Daybreak is a national British breakfast programme, broadcast weekdays on ITV. It is presented live from The London Studios and contains a mixture of news, sport, weather, and entertainment items. The programme was originally presented by Christine Bleakley and Adrian Chiles until their departure on 5 December 2011. They were replaced by Kate Garraway and Dan Lobb, who presented the show on an interim basis, however since 2012, Daybreak has been presented by Lorraine Kelly and Aled Jones, with Ranvir Singh and Matt Barbet hosting the first hour of the programme. Laura Tobin acts as the weather presenter with Richard Arnold presenting the showbiz slot on the show. Helen Fospero, Louisa James and John Stapleton act as stand-in presenters of the main show.",
    average_rating: 1,
    type: "tv",
    id: 33133,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/lPsSVqXFott193XjMpBS2qNsdWw.jpg",
    title: "MTV Movie & TV Awards",
    character: "Herself",
    overview:
      "The annual film & TV awards show presented by MTV. The nominees are decided by producers and executives at MTV with winners decided online by the general public.",
    average_rating: 7.5,
    type: "tv",
    id: 13667,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/oxLO2ROvzS6oGNFaweV745wynP8.jpg",
    title: "Good Morning America",
    character: "Herself",
    overview:
      'Good Morning America is a daily American television show on the ABC television network. The program features news, interviews, weather forecasts, special-interest stories, and segments such as "Pop News" and "Play of the Day". It is produced by ABC News and broadcasts from the Times Square Studios in New York City.',
    average_rating: 5,
    type: "tv",
    id: 556,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/jWkSJ1BV4jCrsf0sewdHppjsQV.jpg",
    title: "Fantastic",
    character: "Herself",
    overview:
      "Fantástico is a Brazilian weekly television newsmagazine broadcast on Sundays on Rede Globo.",
    average_rating: 6,
    type: "tv",
    id: 19538,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Critics' Choice Movie Awards",
    character: "Herself",
    overview:
      "The Critics' Choice Movie Awards are bestowed annually by the Broadcast Film Critics Association to honor the finest in cinematic achievement.",
    average_rating: 5.5,
    type: "tv",
    id: 60971,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Tinseltown TV",
    character: "Herself",
    overview: "",
    average_rating: 0,
    type: "tv",
    id: 30331,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dHjXgLhu7M4Tq6GUbs4m6BZ4HbS.jpg",
    title: "Late Show with David Letterman",
    character: "Herself",
    overview:
      "Late Show with David Letterman is an American late-night talk show hosted by David Letterman on CBS. The show debuted on August 30, 1993, and is produced by Letterman's production company, Worldwide Pants Incorporated and CBS Television Studios. The show's music director and band-leader of the house band, the CBS Orchestra, is Paul Shaffer. The head writer is Matt Roberts and the announcer is Alan Kalter. Of the major U.S. late-night programs, Late Show ranks second in cumulative average viewers over time and third in number of episodes over time. The show leads other late night shows in ad revenue with $271 million in 2009.\n\nIn most U.S. markets the show airs at 11:35 p.m. Eastern/Pacific time, but is recorded Monday through Wednesday at 4:30 p.m., and Thursdays at 3:30 p.m and 6:00 p.m. The second Thursday episode usually airs on Friday of that week.\n\nIn 2002, Late Show with David Letterman was ranked No. 7 on TV Guide's 50 Greatest TV Shows of All Time. CBS has a contract with Worldwide Pants to continue the show through 2014; by then, Letterman will surpass Johnny Carson as the longest tenured late-night talk show host.",
    average_rating: 6.5,
    type: "tv",
    id: 498,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/7N2cJicxK8kss71bLLrq5HA4IB5.jpg",
    title: "Extra",
    character: "Herself",
    overview:
      "Extra is an American entertainment television news program covering events and celebrities which debuted on September 5, 1994 in syndication. It was initially produced at Victory Studios in Glendale, California by Telepictures Productions in association with Warner Bros. Television Distribution. From 1995-2003 it was distributed by Time-Telepictures Television a joint merger between Time Magazine and Telepictures. Extra also had a spinoff show called Celebrity Justice, which ran for only three seasons from 2002–2005. Extra is one of two Warner Bros. Television shows to be syndicated to NBCUniversal television stations, the other being The Ellen DeGeneres Show. Extra is also one of two WBTV entertainment programs, the other being TMZ on TV.",
    average_rating: 2,
    type: "tv",
    id: 5129,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/PhUYIGUUk1RzWq2Aw3TqH65McE.jpg",
    title: "The Ellen DeGeneres Show",
    character: "Self",
    overview:
      "The Ellen DeGeneres Show, often shortened to just Ellen, is an American television talk show hosted by comedian/actress Ellen DeGeneres.",
    average_rating: 6.4,
    type: "tv",
    id: 562,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dUarLANS82FgBOHjRnJw42FB1z4.jpg",
    title: "Saturday Night Live",
    character: "Self - Host",
    overview:
      "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
    average_rating: 7,
    type: "tv",
    id: 1667,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dUarLANS82FgBOHjRnJw42FB1z4.jpg",
    title: "Saturday Night Live",
    character: "Ivanka Trump (uncredited)",
    overview:
      "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
    average_rating: 7,
    type: "tv",
    id: 1667,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500null",
    title: "Goldene Kamera Verleihung",
    character: "herself",
    overview: "",
    average_rating: 0,
    type: "tv",
    id: 89139,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/a6XCdRzASd3JGHtZ6wy0IMHxZTi.jpg",
    title: "Buenas noches y Buenafuente",
    character: "Herself - Interviewee",
    overview: "",
    average_rating: 4.5,
    type: "tv",
    id: 60976,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dQAv70DH7VycuRS6jEX7xAZ9OmW.jpg",
    title: "The Late Show with Stephen Colbert",
    character: "Self",
    overview:
      'Improv actor and comic Stephen Colbert leaves his "The Colbert Report" character behind as he makes his long-awaited return to television. As the host of The Late Show franchise redux -- taped at the historic Ed Sullivan Theatre at New York -- Colbert talks to actors, athletes, politicians, comics, artists and musicians as himself for the first time. Loyal fans, however, will also be treated to consistency as Colbert remains backed by many members of his writing and digital team from his former venture. Julliard-trained Jon Batiste serves as the bandleader.',
    average_rating: 6.6,
    type: "tv",
    id: 63770,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/dUarLANS82FgBOHjRnJw42FB1z4.jpg",
    title: "Saturday Night Live",
    character: "",
    overview:
      "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
    average_rating: 7,
    type: "tv",
    id: 1667,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/mFbKTO5OyxLxpWBfsB6wkiQFVuu.jpg",
    title: "The Tonight Show Starring Jimmy Fallon",
    character: "Self",
    overview:
      "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
    average_rating: 6.2,
    type: "tv",
    id: 59941,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/vVRW8Mdfkq0pCtdeRIIXWQhbRUt.jpg",
    title: "Close Up with The Hollywood Reporter",
    character: "Self",
    overview:
      "Some of this year's most talked about talent open up about the challenges and triumphs of creating critically acclaimed series and performances.",
    average_rating: 6,
    type: "tv",
    id: 63498,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/qVaWwaFmIJC8ZzvayRvClmesXOM.jpg",
    title: "Hot Ones",
    character: "Herself",
    overview:
      "The show with hot questions and even hotter wings invites a famous guest over to eat and then interviews them while they're struggling through the heat.",
    average_rating: 7.5,
    type: "tv",
    id: 72649,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/EpDuYIK81YtCUT3gH2JDpyj8Qk.jpg",
    title: "Marvel Studios: Legends",
    character: "Natasha Romanoff / Black Widow (archive footage)",
    overview:
      "Revisit the epic heroes, villains and moments from across the MCU in preparation for the stories still to come. Each dynamic segment feeds directly into the upcoming series — setting the stage for future events. This series weaves together the many threads that constitute the unparalleled Marvel Cinematic Universe.",
    average_rating: 7.6,
    type: "tv",
    id: 114695,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/25RJm3FmH8to42K5ZT9cGs6KUhY.jpg",
    title: "Finding Your Roots",
    character: "Self",
    overview:
      "Noted Harvard scholar Henry Louis Gates, Jr.  has been helping people discover long-lost relatives hidden for generations within the branches of their family trees.  Professor Gates utilizes a team of genealogists to reconstruct the paper trail left behind by our ancestors and the world’s leading geneticists to decode our DNA and help us travel thousands of years into the past to discover the origins of our earliest forebears.",
    average_rating: 7.5,
    type: "tv",
    id: 43221,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/2RAbC1bwYvE3kYr6PdYFUo6vmO6.jpg",
    title: "WHIH Newsfront",
    character: "Natasha Romanoff / Black Widow",
    overview:
      "WHIH Newsfront is a television program presented by Christine Everhart in the WHIH World News network, informing about major events from political, scientific, and entertainment news, in the Marvel Cinematic Universe.",
    average_rating: 6.4,
    type: "tv",
    id: 69069,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    title: "Loki",
    character: "Natasha Romanoff / Black Widow (archive footage) (uncredited)",
    overview:
      "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
    average_rating: 8.2,
    type: "tv",
    id: 84958,
  },
  {
    poster: "https://image.tmdb.org/t/p/w500/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
    title: "LIVE with Kelly and Ryan",
    character: "Self - Guest",
    overview:
      "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
    average_rating: 5.4,
    type: "tv",
    id: 1900,
  },
];
